server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DATABASE_USUARIOS}
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    hibernate: 
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: microservice-usuario
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true