server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
           allowedOrigins: "http://localhost:4200"
           allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
           allowedHeaders: ["*"]
      routes:
        - id: usuario
          uri: lb://msvc-usuario
          predicates:
            - Path=/gpp/usuario/**
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/gpp/auth/**
        - id: transaccion
          uri: lb://msvc-transacciones
          predicates:
            - Path=/gpp/transaccion/**
        - id: meta
          uri: lb://msvc-metas
          predicates:
            - Path=/gpp/metas/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"