server:
  port: 9092

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DATABASE_TRANSACCIONES}
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    hibernate: 
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka	